# Generated by Django 4.2.2 on 2023-10-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = []
