# Generated by Django 4.2.2 on 2023-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_remove_employee_ename_employee_efirst_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="efirst_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="elast_name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
