# Generated by Django 4.2.2 on 2023-10-20 15:15

from django.db import migrations, models
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_alter_employee_efirst_name_alter_employee_elast_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="eid",
            field=models.CharField(
                max_length=5, validators=[employee.validators.validate_employee_id]
            ),
        ),
    ]
