# Generated by Django 4.2.2 on 2023-10-20 15:17

from django.db import migrations, models
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_alter_employee_eid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="eid",
            field=models.CharField(
                max_length=20, validators=[employee.validators.validate_employee_id]
            ),
        ),
    ]
