# Generated by Django 4.2.2 on 2023-10-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_alter_employee_econtact_alter_employee_eid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="econtact",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="eemail",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
