# Generated by Django 4.2.2 on 2023-10-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_employee_econtact_alter_employee_eemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="eemail",
            field=models.EmailField(max_length=254),
        ),
    ]
